### ISSUE TITLE
Option to invert blacklisting/whitelisting

### ISSUE THREAD

**Issue by kevin-stuart** [TigerKid001/Owl#1]
There is an action "Disable Owl for this website" to "blacklist" websites if Owl is enabled. So normally, Owl is enabled everywhere and it can be disabled selectively. I would like to know if there is a way to invert this behavior.

Effectively, there should be an action "Enable Owl for this website" to whitelist a site and an option to enable only this whitelist without enabling Owl everywhere.

**Comment by TigerKid001** [comment]
Hi,
Thanks for the feature request. I think implementing this would be very easy, but I wonder if it will be a generally useful feature. But I guess it won't hurt to have it there either. I'll aim to get it done with the next update.
Thanks again for using Owl.

**Comment by kevin-stuart** [comment]
This feature was available in other similar extensions. For example, check out the Chrome extension "Deluminate". Once enabled, you could select the "default mode" and then specify explicit rules per site.

My use case is fairly simple: Some bright themes, which want to have dark, even during the day, when I would normally keep normal reading mode.
Also, for a lot of my frequent sites I have selected "dark themes" when logged in, so Owl would invert them; I would have to exclude all of them, so this behavior is better suited to my personal workflow.

Thanks for listening. Owl is already very nice to use and very promising.

**Comment by TigerKid001** [comment]
The use case makes it clearer. I believe Owl can use such an option. Thanks for the suggestion. I'll try to get in the next update (probably by the end of this month).
Thanks for using Owl, I'm glad you like it.

**Comment by TigerKid001** [comment]
Fixed in 7e5ccf2
