### ISSUE TITLE
WebExtension port for Firefox 57

### ISSUE THREAD

**Issue by bemug** [TigerKid001/Owl#22]
As of Firefox 57, Owl can't run anymore because it has not been ported to WebExtension.
Is there any plans on that? Will Owl v3 be a WebExtension?

**Comment by TigerKid001** [comment]
The Fx57+ version of Owl is already in the works and should be ready this weekend. I'll aim to get it available on AMO within the next week.

**Comment by bemug** [comment]
Updated from AMO and working as of today. Thanks for the work.
