### ISSUE TITLE
Configuration panel no more shows up when I double click on the Own icon

### ISSUE THREAD

**Issue by koutheir** [TigerKid001/Owl#25]
Configuration panel no more shows up when I double click on the Own icon. Instead, I get the toolbar menu "Move to menu; Remove from toolbar; ...". Using Firefox 52.3.0 (64-bit) on Linux.

**Comment by TigerKid001** [comment]
Hi, 
Following the 2.1.x updates, Owl will no longer have the drop-down panel from the button. The panel has been moved to the URL bar instead.
