### ISSUE TITLE
Invert SVG?

### ISSUE THREAD

**Issue by kcning** [TigerKid001/Owl#27]
Hi,

Is it possible to add an option to invert SVG? Sometimes when the background is inverted but not the SVG images, they become "hidden". For example, see the SVG image on the wikipedia page:
[without owl](https://screenshots.firefox.com/BRLXRhKa6eF5N8L5/en.wikipedia.org)

and with Owl it becomes
[with owl](https://screenshots.firefox.com/SZmSvzpVb18TAeeC/en.wikipedia.org)

**Comment by TigerKid001** [comment]
Hi,
This has been a long-standing issue. Thanks for opening the ticket, adding to be milestone.

**Comment by Novite5** [comment]
this situation occurs again on firefox 63.0.3 with linux.
